import { OnInit, EventEmitter } from '@angular/core';
import { Location } from '@angular/common';
import { RouteInfo } from '../../tcmcore-objects/tcmcore.domain.objects';
import { IUserSettingsService, IAuthService, IThemeService, ITCMWebSocketService, CoreState } from '../../tcmcore-objects/tcmcore.domain.interfaces';
import { MatDialog } from '@angular/material';
import { Router } from '@angular/router';
import { Store } from '@ngrx/store';
import { TranslateService } from 'ng2-translate';
export declare class NavbarComponent implements OnInit {
    private router;
    private config;
    private location;
    private translate;
    private messageService;
    private themeService;
    private userSettings;
    private dialog;
    private auth;
    private store;
    listTitles: any[];
    homePath: string;
    menuItem: RouteInfo;
    notification: EventEmitter<void>;
    pendingMessages: number;
    isAutheticated: boolean;
    inboxItems: any;
    userName: string;
    theme: string;
    isCollapsed: boolean;
    showSettings: boolean;
    showVoiceSearch: boolean;
    showNotification: boolean;
    Routes: any;
    constructor(router: Router, config: any, location: Location, translate: TranslateService, messageService: ITCMWebSocketService, themeService: IThemeService, userSettings: IUserSettingsService, dialog: MatDialog, auth: IAuthService, store: Store<CoreState>);
    processSelection(item: any): void;
    translateDecode(text: any): any;
    convertCharCodes: (stringToFormat: any) => any;
    openNotification(): void;
    openDialog(): void;
    openDialogVoice(): void;
    CombinePaths(parent: any, child: any): string;
    MainMenuSelect(mainMenuItem: RouteInfo): void;
    ngOnInit(): void;
    ngAfterViewInit(): void;
    stickNavbarOntop: () => void;
    setUserName: (name: any) => void;
    changeTheme(theme: any): void;
    getTitle(): any;
}
